// Generated by Qodo Gen
import { describe, expect, it } from "@jest/globals";
import { createMapKeyedOn } from "./index";

describe("createMapFromWithKey", () => {
  // Creates map from array of objects using specified string key
  it("should create map with string key as index when given array of objects", () => {
    const input = [
      { id: "a", value: 1 },
      { id: "b", value: 2 },
    ];

    const result = createMapKeyedOn(input, "id");

    expect(result).toEqual({
      a: { id: "a", value: 1 },
      b: { id: "b", value: 2 },
    });
  });

  // Handles objects with missing key property
  it("should skip objects with missing key property", () => {
    const input = [
      { id: "a", value: 1 },
      { value: 2 } as any,
      { id: "c", value: 3 },
    ];

    const result = createMapKeyedOn(input, "id");

    expect(result).toEqual({
      a: { id: "a", value: 1 },
      c: { id: "c", value: 3 },
    });
  });
});
